# Generated by Django 4.0.6 on 2022-07-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('where', models.CharField(choices=[('FR', 'Fridge'), ('DR', 'Door'), ('BR', 'Wall Board'), ('OT', 'Other')], default='FR', max_length=2)),
                ('magnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.magnet')),
            ],
        ),
    ]
