# Generated by Django 4.0.6 on 2022-07-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_surface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='surface',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='surface',
            name='date',
            field=models.DateField(verbose_name='Displayed date'),
        ),
        migrations.AlterField(
            model_name='surface',
            name='where',
            field=models.CharField(choices=[('FR', 'Fridge'), ('DR', 'Door'), ('BR', 'Wall Board'), ('OT', 'Other')], default='FR', max_length=2, verbose_name='Surface location'),
        ),
        migrations.AddField(
            model_name='magnet',
            name='purposes',
            field=models.ManyToManyField(to='main_app.purpose'),
        ),
    ]
